---
language: ruby
script: "bundle exec $testcmd"
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - rbx
  - jruby
env:
  - testcmd="qed -Ilib"
  - testcmd="rubytest -Ilib -r./test/helper.rb test/unit"
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby
cache: bundler

